### ISSUE TITLE
still get error message

### ISSUE THREAD

**Issue by LiamKao** [pyliaorachel/python-import-traps#1]
```
➜  sample_package git:(master) python3 -m sample_module_import.py
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 174, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.5/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/home/{username}/src/python/python-import-traps/module_package_basics/sample_package/sample_module_import.py", line 5, in <module>
    from .sample_module import sample_func
SystemError: Parent module '' not loaded, cannot perform relative import

```

**Comment by LiamKao** [comment]
> ```
> ➜  sample_package git:(master) python3 -m sample_module_import.py
> Traceback (most recent call last):
>   File "/usr/lib/python3.5/runpy.py", line 174, in _run_module_as_main
>     mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
>   File "/usr/lib/python3.5/runpy.py", line 109, in _get_module_details
>     __import__(pkg_name)
>   File "/home/{username}/src/python/python-import-traps/module_package_basics/sample_package/sample_module_import.py", line 5, in <module>
>     from .sample_module import sample_func
> SystemError: Parent module '' not loaded, cannot perform relative import
> ```

I got it..., I should run it at sample_package_basics, thanks
